### PR TITLE
Update check_token to reflect url change

### PR DESCRIPTION
**Pull request by zecoj**
vip.symantec.com changed the token check url. This patch fixes it.

### CODE REVIEW

**Comment by dlenski** [comment]
I confirmed that this works and merged it into [dlenski/python-vipaccess](/dlenski/python-vipaccess) as well. Thanks @zecoj!

**Comment by ksylvan** [comment]
Does this still work? About to generate some tokens for use in Authy (instead of using the Symantec VIP Access app).

**Comment by dlenski** [comment]
> Does this still work?

My fork (https://github.com/dlenski/python-vipaccess) is definitely still working, and this PR was already merged into it.

**Comment by ksylvan** [comment]
@dlenski Thank you. What is the diff between your `cli` and `master` branches in your fork? `cli` seems to be 8 commits ahead and `master` is 19 commits ahead of the original upstream.

**Comment by dlenski** [comment]
@ksylvan `cli` is just an old name I forgot to remove… deleted now.

**Comment by ksylvan** [comment]
@dlenski Great. Thanks. That will reduce confusion. I'm going to create a docker container version of this tool (auto-build generated on Docker Hub) so that one can just `docker run ...` the tool.

**Comment by dlenski** [comment]
Sounds good. Glad it's useful!

**Comment by cyrozap** [comment]
Closing this PR since I'm no longer maintaining this project and will be archiving it soon.

**Pull request closed without merging**
